application:
  max-allowed-books: 15
#spring:
 # datasource:
 #   url: jdbs:postgresql://localhost:5432/mybooks
  #  username: myuser
   # password: mu
    #driver-class-name: org.postgresql.Driver
  #jpa:
   # hibernate:
    #  ddl-auto: update
    #show-sql: true

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
